// <auto-generated />
namespace I4DABH1NE84070.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class OrganizationChange : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(OrganizationChange));
        
        string IMigrationMetadata.Id
        {
            get { return "201802182030130_OrganizationChange"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
